### ISSUE TITLE
"Check Broken URLs" job has an exceptional error.

### ISSUE THREAD

**Issue by IsuminI** [john0isaac/markdown-checker#84]
**Describe the bug**
For valid URLs, the "Check Broken URLs" job displays errors for some URLs.
This issue might be related to `microsoft/generative-ai-for-beginners#635`
https://github.com/microsoft/generative-ai-for-beginners/pull/635

**Expected behavior**
A response with a status code of 200 from a HEAD or GET request should not be included in the error list.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 130.0.6723.117

**Additional context**
I'm not sure but, It seems that the tool is also checking other Markdown files that are not related to the intended PR.

This is my first time creating a bug report, so it might not be perfect. Thank you for your understanding.

**Comment by john0isaac** [comment]
Last week there was an update for tech community platform.
We released a new version of the packages to fix this. https://github.com/john0isaac/markdown-checker/releases/tag/v0.2.2

Please re-trigger the workflow and it should work.
If not report it as an issue.

**Comment by IsuminI** [comment]
Thank you very much!
Have a nice day :)

**Comment by john0isaac** [comment]
You too!
