### ISSUE TITLE
Additional Error in "Check Broken URLs"

### ISSUE THREAD

**Issue by IsuminI** [john0isaac/markdown-checker#85]
**Describe the bug**
Through Issue #84, I confirmed that the Markdown checker version in [this repository](https://github.com/microsoft/generative-ai-for-beginners) has been updated to 0.2.2. I verified that the following two links pass without any issues:

- https://techcommunity.microsoft.com/blog/educatordeveloperblog/azure-openai-service-is-now-generally-available/3719177?WT.mc_id=academic-105485-koreyst

- https://techcommunity.microsoft.com/blog/fasttrackforazureblog/grounding-llms/3843857?WT.mc_id=academic-105485-yoterada

However, I found that the following link is causing an error:
- https://opensource.org/osd?WT.mc_id=academic-105485-koreyst

https://github.com/microsoft/generative-ai-for-beginners/actions/runs/12005917466/job/33463433188?pr=640 (job action site)
When tested locally, this link did not show any problems.

**Expected behavior**
The URL should not be included in the error list.

**Screenshots**
![image](https://github.com/user-attachments/assets/2a313c67-e36f-49cb-b5c2-6e2488e8e0e7)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 131.0.6778.86

**Additional context**
I'm not very experienced with writing issues, so if there's anything incorrect, I'd appreciate it if you could let me know. Thank you! 😊

**Comment by john0isaac** [comment]
We will add this domain to skipped domains list.
PRs are welcome!

Thanks for reporting!

**Comment by IsuminI** [comment]
Should I understand this as meaning that I should send the PR myself? I'm leaving a comment because I'm not good at English.
Thank you!

**Comment by john0isaac** [comment]
if you want yes feel free to do so

all you need to do is to add it to this list:
https://github.com/john0isaac/markdown-checker/blob/2f0aa541e7bf3adbe19f8e7f72e1978335c438b6/src/markdown_checker/__init__.py#L75C9-L98C10

**Comment by IsuminI** [comment]
Thank you so much!

**Comment by john0isaac** [comment]
@IsuminI released 🎉 https://pypi.org/project/markdown-checker/0.2.3/#history
